### ISSUE TITLE
Add support for websocket and subscriptions

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot-testnet-faucet#82] opened 2021-10-01 09:41 UTC
Currently, for some reasons, the server only support `http`. That prevents from benefiting from subscriptions.

ref. #67

**Comment by PierreBesson** [comment] 2022-02-07 09:38
I think migrating to the Websocket provider might make the Faucet more resistant to the disconnects that happen when we upgrade RPC nodes which are currently breaking the Westend and Rococo faucets frequently. So it would be nice to see this addressed.

**Comment by PierreBesson** [comment] 2023-01-27 16:53
In my opinion this feature is very important. WS connections have been the standard for connecting to RPC nodes for many years by now.

**Comment by mordamax** [comment] 2023-01-27 17:05
@PierreBesson thanks for emphasising it! That seems to be related/duplicate of this issue https://github.com/paritytech/substrate-matrix-faucet/issues/84 right?
if so, @parutger might be able to provide some timeline on fixing this

**Comment by PierreBesson** [comment] 2023-01-27 17:42
Those are separate issues but it's possible that part of the answer to fix #84 is to switch from HTTP to WS.

**Comment by mutantcornholio** [comment] 2023-05-30 08:55
As of today, all faucets are using websocket RPCs

**Closed by mutantcornholio** 2023-05-30 08:55 UTC
Labels: enhancement
